### ISSUE TITLE
Extended logging needed

### ISSUE THREAD

**Issue by Phu2** [hbz/strapi-rpb#35]
There are 2 drawbacks with the current logging:

1. Sparse notes

In case someone deletes 50 entries via the GUI, this event occurs in Strapi's output stream as a short note which reads like "bulk delete". We would like something more descripitive, eg. the ids of the deleted items.

2. Non-permanent log files

The output inside the container is captured by Docker (accessible via the [docker container logs](https://docs.docker.com/reference/cli/docker/container/logs/) command) and stored by default on the host in

`/var/lib/docker/containers/<container-id>/<container-id>-json.log`
or 
`/var/lib/docker/<namespace>/containers/<container-id>/<container-id>-json.log` if [user namespace mapping](https://docs.docker.com/engine/security/userns-remap/) is in play.
Docker will overwrite this file when the container is restarted.

Looking for a solution on the web i found [this guide](https://www.restack.io/docs/strapi-knowledge-strapi-4-logger-guide). Maybe a good starting point, @fsteeg ?

**Comment by Phu2** [comment]
See also Strapi's official docs: https://docs.strapi.io/dev-docs/configurations/middlewares#logger

**Comment by Phu2** [comment]
Another option: https://github.com/Marje3PSUT/strapi-plugin-audit-log-marje3

**Comment by Phu2** [comment]
We will copy the json container logs to the strapi project directory. Via daily cron. Right before stopping the container and backing up the database. Copied log files will be rotated monthly by logrotate.

**Comment by fsteeg** [comment]
> Are you fine with this approach, @fsteeg ?

Yes, sounds good! :+1:

**Comment by Phu2** [comment]
Thx, closing.
