### ISSUE TITLE
Postgres-related errors in production logs

### ISSUE THREAD

**Issue by fsteeg** [hbz/strapi-rpb#55]
I noticed errors in the logs on production (while investigating [problems with the Strapi export](https://jira.hbz-nrw.de/browse/RPB-202?focusedId=327976&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-327976)), e.g.:

`ERROR:  could not resize shared memory segment "/PostgreSQL.570732038" to 16777216 bytes: No space left on device`

Didn't see any errors in the app yet.

@Phu2 Does this error sound familiar to you? Didn't we have something similar before?

**Comment by Phu2** [comment]
Sounds like we are hitting the shared memory size of 64MB docker is applying per default to containers. See eg. https://stackoverflow.com/questions/56751565/pq-could-not-resize-shared-memory-segment-no-space-left-on-device

Raising this limit in the docker compose files will probably fix this issue. I will open a PR.
